job.type: train
dataset.name: fb15k-237

import: [transformer]
model: reciprocal_relations_model
reciprocal_relations_model.base_model.type: transformer

train:
  optimizer: Adam
  optimizer_args:
    lr: 0.001
    #weight_decay: 0.1
  batch_size: 512
  max_epochs: 500
  loss: kl
  type: 1vsAll
  lr_warmup: 50

KvsAll:
  label_smoothing: 0.1

valid:
  early_stopping:
    patience: 5
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test