job.type: train
dataset.name: fb15k-237

import: [transformer_david]
model: reciprocal_relations_model
reciprocal_relations_model.base_model.type: transformer_david

train:
  optimizer: Adam
  optimizer_args:
    #lr: 0.005
    #lr: 0.001
    lr: 0.0005
    #weight_decay: 0.01
  batch_size: 1024
  max_epochs: 500
  loss: kl
  type: KvsAll
  #lr_warmup: 10
  lr_warmup: 25

transformer_david:
  entity_embedder:
    initialize: xavier_normal_
    dim: 256
  relation_embedder:
    initialize: xavier_normal_
    dim: 256

KvsAll:
  label_smoothing: 0.1
  query_types:
    sp_: True
    s_o: False
    _po: True

valid:
  early_stopping:
#    patience: 5
    patience: 0
  every: 20
  metric: mean_reciprocal_rank_filtered_with_test
