job.type: train
dataset.name: fb15k-237

import: [transformer_david]
model: reciprocal_relations_model
reciprocal_relations_model.base_model.type: transformer_david

#train:
#  optimizer: Adam
#  optimizer_args:
#    #lr: 0.01
#    lr: 0.003
#    #weight_decay: 0.0
#    weight_decay: 0.0001
#  batch_size: 512
#  max_epochs: 200
#  loss: kl
#  type: KvsAll

train:
  optimizer: Adam
  optimizer_args:
    lr: 0.001
    weight_decay: 0.0
  batch_size: 512
  max_epochs: 200
  loss: kl
  type: KvsAll
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_args:
    mode: max
    patience: 2

#transformer_david:
#  entity_embedder:
#    initialize: normal_
#    initialize_args:
#      normal_:
#        mean: 0.0
#        std: 0.02
#  relation_embedder:
#    initialize: normal_
#    initialize_args:
#      normal_:
#        mean: 0.0
#        std: 0.02

transformer_david:
  entity_embedder:
    dim: 200
    initialize: xavier_normal_
  relation_embedder:
    dim: 200
    initialize: xavier_normal_


KvsAll:
  label_smoothing: 0.1
  query_types:
    sp_: True
    s_o: False
    _po: True

valid:
  early_stopping:
    patience: 5
  every: 5
  metric: mean_reciprocal_rank_filtered_with_test
